// <auto-generated />
using System;
using BorrowIt.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Controller.Migrations
{
    [DbContext(typeof(BorrowItContext))]
    partial class BorrowItContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("BorrowIt.Models.RiwayatPinjam", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("IdRuangan")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("NamaPeminjam")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("TanggalKembali")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("TanggalPinjam")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("TrackingToken")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TujuanPinjam")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("IdRuangan");

                    b.ToTable("RiwayatPinjams");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "syauqy@it.student.pens.ac.id",
                            IdRuangan = 2,
                            IsDeleted = false,
                            NamaPeminjam = "Syauqy Arrayyan",
                            Status = "Pending",
                            TanggalKembali = new DateTime(2024, 7, 1, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            TanggalPinjam = new DateTime(2024, 7, 1, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            TrackingToken = "",
                            TujuanPinjam = "Kegiatan welcome party anggota baru ENT 2026."
                        },
                        new
                        {
                            Id = 2,
                            Email = "nabila@it.student.pens.ac.id",
                            IdRuangan = 3,
                            IsDeleted = false,
                            NamaPeminjam = "Nabila Azzahra",
                            Status = "Pending",
                            TanggalKembali = new DateTime(2024, 7, 1, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            TanggalPinjam = new DateTime(2024, 7, 1, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            TrackingToken = "",
                            TujuanPinjam = "Forum komunal mahasiswa teknik elektro."
                        },
                        new
                        {
                            Id = 3,
                            Email = "yayan@it.student.pens.ac.id",
                            IdRuangan = 4,
                            IsDeleted = false,
                            NamaPeminjam = "Yayan Maulana",
                            Status = "Pending",
                            TanggalKembali = new DateTime(2024, 7, 1, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            TanggalPinjam = new DateTime(2024, 7, 1, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            TrackingToken = "",
                            TujuanPinjam = "Rapat kerja kelompok praktikum Rangkaian Listrik."
                        });
                });

            modelBuilder.Entity("BorrowIt.Models.Ruangan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsTersedia")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("JenisRuangan")
                        .HasColumnType("longtext");

                    b.Property<int>("Kapasitas")
                        .HasColumnType("int");

                    b.Property<string>("NamaRuangan")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Ruangans");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 2, 11, 5, 26, 30, 854, DateTimeKind.Utc).AddTicks(358),
                            IsTersedia = true,
                            JenisRuangan = "Laboratorium Praktek",
                            Kapasitas = 30,
                            NamaRuangan = "B302"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 2, 11, 5, 26, 30, 854, DateTimeKind.Utc).AddTicks(1481),
                            IsTersedia = true,
                            JenisRuangan = "Kelas Besar",
                            Kapasitas = 140,
                            NamaRuangan = "SAW 10.08"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 2, 11, 5, 26, 30, 854, DateTimeKind.Utc).AddTicks(1483),
                            IsTersedia = true,
                            JenisRuangan = "Kelas Reguler",
                            Kapasitas = 40,
                            NamaRuangan = "A302"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 2, 11, 5, 26, 30, 854, DateTimeKind.Utc).AddTicks(1484),
                            IsTersedia = true,
                            JenisRuangan = "Kelas Reguler",
                            Kapasitas = 60,
                            NamaRuangan = "A303"
                        });
                });

            modelBuilder.Entity("BorrowIt.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 2, 11, 5, 26, 30, 855, DateTimeKind.Utc).AddTicks(3620),
                            Email = "admin@example.com",
                            PasswordHash = "$2a$11$mo3gmTqO1MrItcFj.DM0C.VvNy6gH4Mmq4Oh4gf3OeAaBIF2/px9y",
                            Username = "Admin"
                        });
                });

            modelBuilder.Entity("BorrowIt.Models.RiwayatPinjam", b =>
                {
                    b.HasOne("BorrowIt.Models.Ruangan", "Ruangan")
                        .WithMany()
                        .HasForeignKey("IdRuangan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ruangan");
                });
#pragma warning restore 612, 618
        }
    }
}
